### ISSUE TITLE
[v5] wrong properties of BalancingRule

### ISSUE THREAD

**Issue by hellodword** [EHfive/v2ray-jsonschema#3]
Currently, for v5, `fallbackTag` should be `fallback_tag` and `outboundSelector` should be `outbound_selector`

- https://github.com/v2fly/v2ray-core/issues/2900#issuecomment-1959100407
- https://github.com/v2fly/v2ray-core/blob/458db3954f76bbf7ce621a24151d9d5469d8b6fb/app/router/config.go#L178-L184

**Comment by EHfive** [comment]
This is kind of inconsistency in V2Ray to use both camelCase protobuf json tag and snake_case json tag for JSON parsing.

I believe it should be addressed in V2Ray to fix this inconsistency, maybe you can file a PR to fix that.

**Comment by hellodword** [comment]
> This is kind of inconsistency in V2Ray to use both camelCase protobuf json tag and snake_case json tag for JSON parsing.
> 
> I believe it should be addressed in V2Ray to fix this inconsistency, maybe you can file a PR to fix that.

Yeah, they're confusing. 

I dived into the source today, finally I closed my PRs and proposals, decided to give up v2fly and migrate to sing-box, it's well-documented.

Thanks for your work, really helpful.
